env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  'no-constant-condition':
    - 'error'
    - checkLoops: false
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  '@typescript-eslint/no-this-alias': 'off'
ignorePatterns:
  - '**/*.js'
  - '**/*.d.ts'
